node {

  checkout scm

  def branch = env.BRANCH_NAME
  def build_number = env.BUILD_NUMBER

  stage('Build') {
    sh "docker build -t registry:5000/basic-node-service:${branch}-${build_number} ."
  }

  stage('Push') {
    sh "docker push registry:5000/basic-node-service:${branch}-${build_number}"
  }

  stage('Deploy')  {
    sh "cat deploy.yaml | sed 's/IMAGE/registry:5000\/basic-node-service:${branch}-${build_number}/g > stack_file.yaml"
    sh "cat stack_file.yaml"
    sh "docker stack deploy -c stack_file.yaml basic_node_service"
  }

}
