version: '3'

services:
  nginx:
    image: wcschlosser/nginx-rpi:0.1.0
    ports:
    - "80:80"
    networks:
    - pi-swarm
    deploy:
      replicas: 1
      placement:
        constraints:
        - node.role == manager

networks:
  pi-swarm:
    external: true
