FROM resin/rpi-raspbian:jessie-20170816

RUN apt-get -y update && \
    apt-get install -y nginx

EXPOSE 80

RUN ln -sf /dev/stdout /var/log/nginx/access.log
RUN ln -sf /dev/stderr /var/log/nginx/error.log
RUN rm /etc/nginx/sites-available/*

COPY ./default.conf /etc/nginx/sites-available/default.conf

CMD ["/usr/sbin/nginx", "-g", "daemon off;"]
